# Generated by Django 5.0.6 on 2024-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                ("d_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "d_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "director",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Filming",
            fields=[
                ("f_id", models.IntegerField(primary_key=True, serialize=False)),
                ("m_id", models.IntegerField()),
                ("d_id", models.IntegerField()),
            ],
            options={
                "db_table": "filming",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("m_id", models.IntegerField(primary_key=True, serialize=False)),
                ("m_korname", models.CharField(max_length=255)),
                ("m_engname", models.CharField(blank=True, max_length=255, null=True)),
                ("m_year", models.IntegerField(blank=True, null=True)),
                ("m_type", models.CharField(blank=True, max_length=50, null=True)),
                ("m_status", models.CharField(blank=True, max_length=50, null=True)),
                ("m_company", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "movie",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MovieCountry",
            fields=[
                ("mc_id", models.IntegerField(primary_key=True, serialize=False)),
                ("m_id", models.IntegerField()),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "movie_country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                ("mg_id", models.IntegerField(primary_key=True, serialize=False)),
                ("m_id", models.IntegerField()),
                ("genre_name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "movie_genre",
                "managed": False,
            },
        ),
    ]
